/**
 * GET /api/v1/sources — List of RSS sources used by the pipeline.
 *
 * Reads from web/data/sources.json (pre-generated by scripts/export_sources.py).
 * Falls back to an empty list if the file is missing.
 */

export const dynamic = "force-dynamic";

import fs from "fs";
import path from "path";
import { checkRateLimit, getClientIp } from "@/lib/api/rate-limit";
import { ok, rateLimitExceeded, serverError, optionsResponse } from "@/lib/api/response";

interface SourceEntry {
  name: string;
  url: string;
  region?: string;
  category?: string;
  language?: string;
}

export async function OPTIONS() {
  return optionsResponse();
}

export async function GET(request: Request) {
  const ip = getClientIp(request);
  const rl = checkRateLimit(ip);
  if (!rl.allowed) return rateLimitExceeded(rl);

  try {
    const filePath = path.join(process.cwd(), "data", "sources.json");
    let sources: SourceEntry[] = [];

    if (fs.existsSync(filePath)) {
      const raw = fs.readFileSync(filePath, "utf-8");
      sources = JSON.parse(raw) as SourceEntry[];
    }

    // Return the minimal shape the spec requires (name + url), keeping
    // extra fields (region, category, language) as bonus metadata.
    return ok(
      {
        sources,
        count: sources.length,
      },
      rl
    );
  } catch (err) {
    console.error("[GET /api/v1/sources]", err);
    return serverError();
  }
}
